# Site settings
title: 陈洪的个人博客
email: honchinag@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  陈洪的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://honcen.github.io" # the base hostname & protocol for your site
rss_url: /pages/feed.xml

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

# Social account
twitter:
# weibo:    ID
github: honcen
# codepen:  username
# dribbble: username

# avatar头像及Favicon
avatar: https://avatars3.githubusercontent.com/u/15683014
favicon: http://7xs4tw.com1.z0.glb.clouddn.com/bloglogo.ico

# disqus 设置
disqus:
  shortname: suyan-zh

# google analytics 设置
ga:
  id: UA-54767140-1
  url: honcen.github.io

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
